import 'dotenv/config';
import axios from 'axios';

const BASE = process.env.SCHEDULER_API_BASE || `http://localhost:${process.env.PORT || 3000}`;

async function createAndProcess(title, content) {
  try {
    const create = await axios.post(`${BASE}/api/news`, {
      title,
      content,
      source: 'scheduler',
      sourceUrl: ''
    }, { timeout: 15000 });
    const newsId = create.data?.newsId;
    if (!newsId) throw new Error('missing_newsId');
    await axios.post(`${BASE}/api/bhiv/process`, { newsItemId: newsId }, { timeout: 60000 });
    console.log(`[scheduler] processed ${newsId} -> ${title}`);
  } catch (err) {
    console.error('[scheduler] error', err?.message || err);
  }
}

function scheduleCategory(name, intervalMs, builder) {
  console.log(`[scheduler] ${name} every ${Math.round(intervalMs / 60000)} min`);
  const run = async () => {
    const payload = builder();
    await createAndProcess(payload.title, payload.content);
  };
  // Run once immediately
  run();
  // Then at interval
  setInterval(run, intervalMs);
}

function nowIso() {
  return new Date().toISOString();
}

// Live: every 15 minutes
scheduleCategory('Live', 15 * 60 * 1000, () => ({
  title: `Live Update ${nowIso()}`,
  content: 'Automated live update from scheduler.'
}));

// Finance: every hour
scheduleCategory('Finance', 60 * 60 * 1000, () => ({
  title: `Finance Brief ${nowIso()}`,
  content: 'Automated finance brief generated by scheduler.'
}));

// World/Kids/Regional: every 6 hours
scheduleCategory('World', 6 * 60 * 60 * 1000, () => ({
  title: `World Highlights ${nowIso()}`,
  content: 'Automated world highlights prepared for periodic review.'
}));

scheduleCategory('Kids', 6 * 60 * 60 * 1000, () => ({
  title: `Kids Edition ${nowIso()}`,
  content: 'Age-appropriate news summary for kids.'
}));

scheduleCategory('Regional', 6 * 60 * 60 * 1000, () => ({
  title: `Regional Digest ${nowIso()}`,
  content: 'Regional updates and summaries.'
}));

console.log('[scheduler] started');
